/**
 * The only place the interface talks to the colour core.
 *
 * Nothing here decides anything. Routing, fidelity and what actually
 * landed are the core's answers; this file carries them across and adds
 * no opinions of its own.
 */

import { invoke } from "@tauri-apps/api/core";
import type {
  ApplyReport,
  ColorState,
  GammaRangeOutcome,
  LutTarget,
  Snapshot,
} from "./bindings";
import previewSnapshot from "./preview-snapshot.json";

/**
 * False in a plain `bun run dev` browser session, where no Rust core
 * exists. The interface says so in a banner rather than quietly drawing
 * as though something were being applied.
 */
export function isTauri(): boolean {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

/**
 * What the surface draws with no core attached.
 *
 * Generated by `cargo test` from the real router, so the stage and
 * fidelity columns are not a second implementation of the routing rules —
 * they are the same answers the core gives for an ordinary SDR desktop.
 * The displays in it are placeholders and nothing is being written.
 */
export const PREVIEW: Snapshot = previewSnapshot as Snapshot;

export function loadSnapshot(): Promise<Snapshot> {
  if (!isTauri()) return Promise.resolve(PREVIEW);
  return invoke<Snapshot>("get_snapshot");
}

export function applyState(
  state: ColorState,
  target: LutTarget,
): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport(state));
  return invoke<ApplyReport>("apply_state", { state, target });
}

export function setEnabled(enabled: boolean): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport(PREVIEW.state));
  return invoke<ApplyReport>("set_enabled", { enabled });
}

export function setLutTarget(target: LutTarget): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport(PREVIEW.state));
  return invoke<ApplyReport>("set_lut_target", { target });
}

export function restoreDisplay(): Promise<void> {
  if (!isTauri()) return Promise.resolve();
  return invoke<void>("restore_display");
}

export function unlockGammaRange(): Promise<GammaRangeOutcome> {
  if (!isTauri()) {
    return Promise.resolve({
      kind: "failed",
      reason: "there is no colour core in a browser session",
    });
  }
  return invoke<GammaRangeOutcome>("unlock_gamma_range");
}

/** A report that reached nothing, because nothing was there to reach. */
function previewReport(_state: ColorState): ApplyReport {
  return { reports: PREVIEW.channels, stages: [], micros: 0, dirty: false };
}
