/**
 * The only place the interface talks to the colour core.
 *
 * Nothing here decides anything. Routing, fidelity, which preset matched
 * and what actually landed are the core's answers; this file carries them
 * across and adds no opinions of its own.
 */

import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import type {
  Action,
  ApplyReport,
  ColorState,
  Foreground,
  GammaRangeOutcome,
  LutTarget,
  Registration,
  ResidencyView,
  ScanReport,
  Snapshot,
} from "./bindings";
import previewSnapshot from "./preview-snapshot.json";

/**
 * False in a plain `bun run dev` browser session, where no Rust core
 * exists. The interface says so in a banner rather than quietly drawing
 * as though something were being applied.
 */
export function isTauri(): boolean {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

/**
 * What the surface draws with no core attached.
 *
 * Generated by `cargo test` from the real router, so the stage and
 * fidelity columns are not a second implementation of the routing rules —
 * they are the same answers the core gives for an ordinary SDR desktop.
 * The displays and the second preset are placeholders and nothing is
 * being written.
 */
export const PREVIEW: Snapshot = previewSnapshot as Snapshot;

/** Mirrors `Activated` in `src-tauri/src/lib.rs`. */
export interface Activated {
  foreground: Foreground;
  snapshot: Snapshot;
}

const NO_CORE = "there is no colour core in a browser session";

function refuse<T>(): Promise<T> {
  return Promise.reject(new Error(NO_CORE));
}

export function loadSnapshot(): Promise<Snapshot> {
  if (!isTauri()) return Promise.resolve(PREVIEW);
  return invoke<Snapshot>("get_snapshot");
}

export function applyState(state: ColorState, target: LutTarget): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport());
  return invoke<ApplyReport>("apply_state", { state, target });
}

export function setEnabled(enabled: boolean): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport());
  return invoke<ApplyReport>("set_enabled", { enabled });
}

/**
 * Hold-to-bypass. The core stands the display down without forgetting the
 * preset, and holds any activation the watcher makes meanwhile — the
 * point of the bypass is a stable comparison.
 */
export function setBypass(bypassed: boolean): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport());
  return invoke<ApplyReport>("set_bypass", { bypassed });
}

export function setLutTarget(target: LutTarget): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport());
  return invoke<ApplyReport>("set_lut_target", { target });
}

export function restoreDisplay(): Promise<void> {
  if (!isTauri()) return Promise.resolve();
  return invoke<void>("restore_display");
}

export function unlockGammaRange(): Promise<GammaRangeOutcome> {
  if (!isTauri()) return Promise.resolve({ kind: "failed", reason: NO_CORE });
  return invoke<GammaRangeOutcome>("unlock_gamma_range");
}

// ── presets ─────────────────────────────────────────────────────────────

export function addPreset(name: string, exe: string | null): Promise<string> {
  if (!isTauri()) return refuse();
  return invoke<string>("add_preset", { name, exe });
}

export function removePreset(id: string): Promise<ApplyReport> {
  if (!isTauri()) return refuse();
  return invoke<ApplyReport>("remove_preset", { id });
}

export function selectPreset(id: string): Promise<ApplyReport> {
  if (!isTauri()) return refuse();
  return invoke<ApplyReport>("select_preset", { id });
}

export function renamePreset(id: string, name: string): Promise<void> {
  if (!isTauri()) return refuse();
  return invoke<void>("rename_preset", { id, name });
}

export function bindPreset(id: string, exe: string | null): Promise<void> {
  if (!isTauri()) return refuse();
  return invoke<void>("bind_preset", { id, exe });
}

/**
 * Fires when the watcher, rather than the person, changed which preset is
 * on the screen. Returns its own unsubscribe.
 */
export function onActivated(handler: (event: Activated) => void): () => void {
  if (!isTauri()) return () => {};
  const pending = listen<Activated>("activated", (e) => handler(e.payload));
  return () => {
    void pending.then((off) => off());
  };
}

/** A report that reached nothing, because nothing was there to reach. */
function previewReport(): ApplyReport {
  return { reports: PREVIEW.channels, stages: [], micros: 0, dirty: false };
}

// ── residency ───────────────────────────────────────────────────────────

/**
 * What Windows allowed, what Azure asked for, and where Azure stands on
 * the machine. One answer rather than four, because the settings screen
 * draws them together.
 */
export function loadResidency(): Promise<ResidencyView> {
  if (!isTauri()) return Promise.resolve(PREVIEW_RESIDENCY);
  return invoke<ResidencyView>("get_residency");
}

/**
 * Binds one action, or clears it when `chord` is null.
 *
 * The chord goes over as the text the capture widget showed. The core
 * parses it, so an unbindable combination comes back as a refusal with a
 * reason rather than being stored and quietly never registered.
 */
export function setBinding(action: Action, chord: string | null): Promise<Registration[]> {
  if (!isTauri()) return refuse();
  return invoke<Registration[]>("set_binding", { action, chord });
}

export function resetBindings(): Promise<Registration[]> {
  if (!isTauri()) return refuse();
  return invoke<Registration[]>("reset_bindings");
}

export function setAutostart(enabled: boolean): Promise<boolean> {
  if (!isTauri()) return refuse();
  return invoke<boolean>("set_autostart", { enabled });
}

/** Relaunches Azure elevated. This process exits if Windows agrees. */
export function restartElevated(): Promise<void> {
  if (!isTauri()) return refuse();
  return invoke<void>("restart_elevated");
}

export function hideToTray(): Promise<void> {
  if (!isTauri()) return Promise.resolve();
  return invoke<void>("hide_to_tray");
}

/**
 * Fires when something outside the window changed the display — a global
 * hotkey, or the tray menu. Returns its own unsubscribe.
 */
export function onSnapshot(handler: (snapshot: Snapshot) => void): () => void {
  if (!isTauri()) return () => {};
  const pending = listen<Snapshot>("snapshot", (e) => handler(e.payload));
  return () => {
    void pending.then((off) => off());
  };
}

/**
 * What the settings screen draws with no core attached: the defaults, and
 * nothing registered, because nothing was asked of Windows.
 */
const PREVIEW_RESIDENCY: ResidencyView = {
  bindings: {
    toggleEnabled: "ALT+SHIFT+V",
    cycleNext: "ALT+SHIFT+RIGHT",
    cyclePrev: "ALT+SHIFT+LEFT",
    restoreDisplay: "CTRL+ALT+SHIFT+R",
    holdBypass: null,
  },
  registrations: [],
  conflicts: [],
  autostart: false,
  elevated: false,
  notices: [],
};

// ── the library scan ────────────────────────────────────────────────────

/**
 * Walks every launcher's bookkeeping. Creates nothing: the candidates
 * come back and the person chooses which become presets.
 */
export function scanLibraries(): Promise<ScanReport> {
  if (!isTauri()) return refuse();
  return invoke<ScanReport>("scan_libraries");
}
