/**
 * The only place the interface talks to the colour core.
 *
 * Nothing here decides anything. Routing, fidelity, which preset matched
 * and what actually landed are the core's answers; this file carries them
 * across and adds no opinions of its own.
 */

import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import type {
  ApplyReport,
  ColorState,
  Foreground,
  GammaRangeOutcome,
  LutTarget,
  Snapshot,
} from "./bindings";
import previewSnapshot from "./preview-snapshot.json";

/**
 * False in a plain `bun run dev` browser session, where no Rust core
 * exists. The interface says so in a banner rather than quietly drawing
 * as though something were being applied.
 */
export function isTauri(): boolean {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

/**
 * What the surface draws with no core attached.
 *
 * Generated by `cargo test` from the real router, so the stage and
 * fidelity columns are not a second implementation of the routing rules —
 * they are the same answers the core gives for an ordinary SDR desktop.
 * The displays and the second preset are placeholders and nothing is
 * being written.
 */
export const PREVIEW: Snapshot = previewSnapshot as Snapshot;

/** Mirrors `Activated` in `src-tauri/src/lib.rs`. */
export interface Activated {
  foreground: Foreground;
  snapshot: Snapshot;
}

const NO_CORE = "there is no colour core in a browser session";

function refuse<T>(): Promise<T> {
  return Promise.reject(new Error(NO_CORE));
}

export function loadSnapshot(): Promise<Snapshot> {
  if (!isTauri()) return Promise.resolve(PREVIEW);
  return invoke<Snapshot>("get_snapshot");
}

export function applyState(state: ColorState, target: LutTarget): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport());
  return invoke<ApplyReport>("apply_state", { state, target });
}

export function setEnabled(enabled: boolean): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport());
  return invoke<ApplyReport>("set_enabled", { enabled });
}

/**
 * Hold-to-bypass. The core stands the display down without forgetting the
 * preset, and holds any activation the watcher makes meanwhile — the
 * point of the bypass is a stable comparison.
 */
export function setBypass(bypassed: boolean): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport());
  return invoke<ApplyReport>("set_bypass", { bypassed });
}

export function setLutTarget(target: LutTarget): Promise<ApplyReport> {
  if (!isTauri()) return Promise.resolve(previewReport());
  return invoke<ApplyReport>("set_lut_target", { target });
}

export function restoreDisplay(): Promise<void> {
  if (!isTauri()) return Promise.resolve();
  return invoke<void>("restore_display");
}

export function unlockGammaRange(): Promise<GammaRangeOutcome> {
  if (!isTauri()) return Promise.resolve({ kind: "failed", reason: NO_CORE });
  return invoke<GammaRangeOutcome>("unlock_gamma_range");
}

// ── presets ─────────────────────────────────────────────────────────────

export function addPreset(name: string, exe: string | null): Promise<string> {
  if (!isTauri()) return refuse();
  return invoke<string>("add_preset", { name, exe });
}

export function removePreset(id: string): Promise<ApplyReport> {
  if (!isTauri()) return refuse();
  return invoke<ApplyReport>("remove_preset", { id });
}

export function selectPreset(id: string): Promise<ApplyReport> {
  if (!isTauri()) return refuse();
  return invoke<ApplyReport>("select_preset", { id });
}

export function renamePreset(id: string, name: string): Promise<void> {
  if (!isTauri()) return refuse();
  return invoke<void>("rename_preset", { id, name });
}

export function bindPreset(id: string, exe: string | null): Promise<void> {
  if (!isTauri()) return refuse();
  return invoke<void>("bind_preset", { id, exe });
}

/**
 * Fires when the watcher, rather than the person, changed which preset is
 * on the screen. Returns its own unsubscribe.
 */
export function onActivated(handler: (event: Activated) => void): () => void {
  if (!isTauri()) return () => {};
  const pending = listen<Activated>("activated", (e) => handler(e.payload));
  return () => {
    void pending.then((off) => off());
  };
}

/** A report that reached nothing, because nothing was there to reach. */
function previewReport(): ApplyReport {
  return { reports: PREVIEW.channels, stages: [], micros: 0, dirty: false };
}
