/**
 * Shapes mirroring the Rust core in `src-tauri`.
 *
 * These are hand-written for now and are REPLACED WHOLESALE by
 * `src/bindings.ts`, generated by tauri-specta, the moment the Rust
 * commands land in M1. Nothing here may become a second source of truth:
 * the colour maths lives in Rust because the effect has to hold with no
 * window open, and the UI only ever renders what the core reports.
 */

export type ChannelId =
  | "vibrance"
  | "saturation"
  | "hue"
  | "brightness"
  | "contrast"
  | "gamma"
  | "temperature"
  | "tint";

/** Which stage of the fixed device path carries a channel. */
export type Stage = "matrix" | "lut";

/**
 * How faithfully a backend can express a channel. Deliberately not a
 * boolean: vibrance is genuinely approximate on both vendor-neutral
 * backends and the interface has to be able to say so.
 */
export type Fidelity = "exact" | "approximate" | "clamped" | "inert" | "unrealised";

export interface Channel {
  id: ChannelId;
  /** Fixed-width key. The field is a table; keys must not vary in width. */
  key: string;
  name: string;
  min: number;
  max: number;
  neutral: number;
  step: number;
  unit: "percent" | "degrees" | "factor";
  stage: Stage;
  fidelity: Fidelity;
  /** Present only when fidelity is not `exact`; states the machine fact. */
  note?: string;
}

export const CHANNELS: Channel[] = [
  {
    id: "vibrance",
    key: "VIB",
    name: "VIBRANCE",
    min: 0,
    max: 200,
    neutral: 100,
    step: 1,
    unit: "percent",
    stage: "matrix",
    fidelity: "approximate",
    note: "5×5 affine matrix cannot express saturation-dependent gain",
  },
  {
    id: "saturation",
    key: "SAT",
    name: "SATURATION",
    min: 0,
    max: 200,
    neutral: 100,
    step: 1,
    unit: "percent",
    stage: "matrix",
    fidelity: "exact",
  },
  {
    id: "hue",
    key: "HUE",
    name: "HUE",
    min: -180,
    max: 180,
    neutral: 0,
    step: 1,
    unit: "degrees",
    stage: "matrix",
    fidelity: "exact",
  },
  {
    id: "brightness",
    key: "BRT",
    name: "BRIGHTNESS",
    min: -50,
    max: 50,
    neutral: 0,
    step: 1,
    unit: "percent",
    stage: "lut",
    fidelity: "exact",
  },
  {
    id: "contrast",
    key: "CON",
    name: "CONTRAST",
    min: 30,
    max: 200,
    neutral: 100,
    step: 1,
    unit: "factor",
    stage: "lut",
    fidelity: "exact",
  },
  {
    id: "gamma",
    key: "GAM",
    name: "GAMMA",
    min: 40,
    max: 280,
    neutral: 100,
    step: 1,
    unit: "factor",
    stage: "lut",
    fidelity: "clamped",
    note: "Windows is clamping this range until GdiIcmGammaRange is unlocked",
  },
  {
    id: "temperature",
    key: "TMP",
    name: "TEMPERATURE",
    min: -100,
    max: 100,
    neutral: 0,
    step: 1,
    unit: "percent",
    stage: "lut",
    fidelity: "exact",
  },
  {
    id: "tint",
    key: "TNT",
    name: "TINT",
    min: -100,
    max: 100,
    neutral: 0,
    step: 1,
    unit: "percent",
    stage: "lut",
    fidelity: "exact",
  },
];

export type ColorState = Record<ChannelId, number>;

export const NEUTRAL: ColorState = CHANNELS.reduce((acc, c) => {
  acc[c.id] = c.neutral;
  return acc;
}, {} as ColorState);

export function formatValue(channel: Channel, raw: number): string {
  switch (channel.unit) {
    case "degrees":
      return `${raw > 0 ? "+" : ""}${raw}°`;
    case "factor":
      return (raw / 100).toFixed(2);
    case "percent":
      return channel.neutral === 0
        ? `${raw > 0 ? "+" : ""}${raw}%`
        : `${raw}%`;
  }
}

/** True when a channel is doing nothing to the screen right now. */
export function isInert(fidelity: Fidelity): boolean {
  return fidelity === "inert" || fidelity === "unrealised";
}

export const FIDELITY_LABEL: Record<Fidelity, string> = {
  exact: "EXACT",
  approximate: "APPROX",
  clamped: "CLAMPED",
  inert: "INERT",
  unrealised: "NO PATH",
};

// ── Session state ───────────────────────────────────────────────────────

export type ActivationMode = "focused" | "running" | "manual";
export type MatchKind = "full path" | "package" | "exe name";

export interface Preset {
  id: string;
  name: string;
  /** null for the desktop default, which binds to nothing. */
  exe: string | null;
  mode: ActivationMode;
  state: ColorState;
}

export interface DisplayInfo {
  key: string;
  name: string;
  primary: boolean;
  hdr: boolean;
}

export interface SessionState {
  enabled: boolean;
  activePresetId: string;
  matchedBy: MatchKind | null;
  exclusiveFullscreen: boolean;
  displays: DisplayInfo[];
  gammaRangeUnlocked: boolean;
}
