// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something a key can be bound to.
 *
 * Every one of these is reachable from the window too. A hotkey is a
 * faster route to an existing action, never the only route — a binding
 * Windows refuses must not take a capability away with it.
 */
export type Action = "toggleEnabled" | "cycleNext" | "cyclePrev" | "restoreDisplay" | "holdBypass";
