// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelReport } from "./ChannelReport";
import type { StageLanding } from "./StageLanding";

/**
 * What actually happened, which is the only thing the surface is allowed
 * to draw.
 */
export type ApplyReport = { reports: Array<ChannelReport>, stages: Array<StageLanding>, 
/**
 * Wall time of the writes, microseconds. The field prints it.
 *
 * u32, not u64: it crosses to JavaScript as a JSON number, and an
 * apply that took over an hour is not a thing that happens.
 */
micros: number, 
/**
 * True while display state differs from the panel's own defaults.
 */
dirty: boolean, };
