// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelReport } from "./ChannelReport";
import type { StageLanding } from "./StageLanding";

/**
 * What actually happened, which is the only thing the surface is allowed
 * to draw.
 */
export type ApplyReport = { reports: Array<ChannelReport>, stages: Array<StageLanding>, 
/**
 * Wall time of the writes, microseconds. The field prints it.
 */
micros: bigint, 
/**
 * True while display state differs from the panel's own defaults.
 */
dirty: boolean, };
