// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BindingSet = { toggleEnabled: string | null, cycleNext: string | null, cyclePrev: string | null, restoreDisplay: string | null, holdBypass: string | null, };
