// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { Launcher } from "./Launcher";

export type Candidate = { name: string, 
/**
 * Full path to the executable.
 */
exe: string, launcher: Launcher, confidence: Confidence, };
