// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The eight controls. Order is the order they are drawn in the field, which
 * is the order of the device path: mix first, then the tone curve.
 */
export type ChannelId = "vibrance" | "saturation" | "hue" | "brightness" | "contrast" | "gamma" | "temperature" | "tint";
