// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { ChannelRange } from "./ChannelRange";
import type { Fidelity } from "./Fidelity";
import type { Stage } from "./Stage";

export type ChannelReport = { id: ChannelId, key: string, name: string, range: ChannelRange, stage: Stage | null, fidelity: Fidelity, 
/**
 * The sub-range that actually reaches the panel when something outside
 * Azure is limiting it. `None` means the whole range is reachable.
 */
reachable: [number, number] | null, 
/**
 * Present whenever fidelity is not `Exact`. States the machine fact.
 */
note: string | null, };
