// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Channel values in UI units: percent, degrees, or factor x100. Integer on
 * purpose — this is what the sliders emit and what the log prints.
 */
export type ColorState = { vibrance: number, saturation: number, hue: number, brightness: number, contrast: number, gamma: number, temperature: number, tint: number, };
