// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the executable was arrived at.
 *
 * Never hidden. A preset bound to the wrong binary simply never fires,
 * and the player's only clue would be that nothing happens — so the
 * guess is labelled a guess where it is offered.
 */
export type Confidence = "exact" | "likely" | "guess";
