// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

/**
 * Two actions asking for the same key. Distinct from Windows refusing a
 * registration, and reported separately: this one is Azure's to fix, the
 * other belongs to whatever program got there first.
 */
export type Conflict = { chord: string, actions: Array<Action>, };
