// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisplayInfo = { 
/**
 * Stable device key, used to target the LUT.
 */
key: string, name: string, primary: boolean, hdr: boolean, };
