// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the machine can do right now. Every field is measured, never
 * assumed; `azure-display::probe` fills it in.
 */
export type Environment = { 
/**
 * The Magnification API initialised and nothing else owns the slot.
 */
matrixAvailable: boolean, 
/**
 * At least one display accepted a gamma ramp handle.
 */
lutAvailable: boolean, 
/**
 * A game is bypassing the compositor, so the matrix reaches nothing.
 */
exclusiveFullscreen: boolean, 
/**
 * Any targeted display is in HDR mode.
 */
hdrActive: boolean, 
/**
 * HKLM ICM GdiIcmGammaRange == 256.
 */
gammaRangeUnlocked: boolean, 
/**
 * Windows Colour Filters owns the fullscreen colour effect. We yield.
 */
colorFiltersActive: boolean, };
