// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How faithfully the routed stage can express a channel. Not a boolean:
 * vibrance is genuinely approximate on both vendor-neutral backends.
 */
export type Fidelity = "exact" | "approximate" | "clamped" | "inert" | "unrealised";
