// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What was in front: its full path when the process would give one up,
 * and always its executable name.
 */
export type Foreground = { path: string | null, exe: string, };
