// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GammaRangeOutcome = { "kind": "unlocked", requires_sign_out: boolean, } | { "kind": "needsElevation" } | { "kind": "failed", reason: string, };
