// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What came of asking Windows to lift the GDI gamma clamp.
 */
export type GammaRangeOutcome = { "kind": "unlocked", requiresSignOut: boolean, } | { "kind": "needsElevation" } | { "kind": "failed", reason: string, };
