/**
 * The Rust core's types, generated by ts-rs when `cargo test` runs.
 *
 * Every file beside this one is generated — do not edit them. This index
 * is hand-written because ts-rs emits one file per type and nothing else;
 * if a name here stops resolving, the Rust type was renamed and the
 * interface has to follow.
 */

export type { Action } from "./Action";
export type { ActivationMode } from "./ActivationMode";
export type { ApplyReport } from "./ApplyReport";
export type { BindingSet } from "./BindingSet";
export type { Candidate } from "./Candidate";
export type { ChannelId } from "./ChannelId";
export type { ChannelRange } from "./ChannelRange";
export type { ChannelReport } from "./ChannelReport";
export type { ColorState } from "./ColorState";
export type { Confidence } from "./Confidence";
export type { Conflict } from "./Conflict";
export type { DisplayInfo } from "./DisplayInfo";
export type { Environment } from "./Environment";
export type { Fidelity } from "./Fidelity";
export type { Foreground } from "./Foreground";
export type { GammaRangeOutcome } from "./GammaRangeOutcome";
export type { Launcher } from "./Launcher";
export type { LutTarget } from "./LutTarget";
export type { MatchKind } from "./MatchKind";
export type { Outcome } from "./Outcome";
export type { Phase } from "./Phase";
export type { Preset } from "./Preset";
export type { Registration } from "./Registration";
export type { ResidencyView } from "./ResidencyView";
export type { ScanReport } from "./ScanReport";
export type { SourceOutcome } from "./SourceOutcome";
export type { SourceReport } from "./SourceReport";
export type { Settings } from "./Settings";
export type { Snapshot } from "./Snapshot";
export type { Stage } from "./Stage";
export type { StageLanding } from "./StageLanding";
export type { Unit } from "./Unit";
