// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a candidate came from. Shown against every result, because
 * "Steam found this" and "Azure guessed this from a folder" deserve
 * different amounts of trust from the person reading the list.
 */
export type Launcher = "steam" | "epic" | "gog" | "ea" | "ubisoft" | "battleNet" | "xbox";
