// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The matrix is desktop-wide; the LUT is the only per-display stage.
 */
export type LutTarget = "all" | { "one": string };
