// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a foreground window was recognised. Not cosmetic: a name match can
 * be the wrong copy of the right game, and the interface says which one
 * happened rather than implying certainty it does not have.
 */
export type MatchKind = "fullPath" | "exeName";
