// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a bound key went down or came back up.
 *
 * Only `HoldBypass` ever reports `Released`. Windows gives a hotkey no
 * release event, so that one is watched for rather than delivered.
 */
export type Phase = "pressed" | "released";
