// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivationMode } from "./ActivationMode";
import type { ColorState } from "./ColorState";

export type Preset = { id: string, name: string, 
/**
 * The executable this preset binds to. `None` for the desktop preset.
 */
exe: string | null, mode: ActivationMode, state: ColorState, };
