// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preset } from "./Preset";

export type PresetSet = { version: number, 
/**
 * The next id to hand out. Stored so a deleted preset's id is never
 * reissued to a different game.
 */
next: number, presets: Array<Preset>, activeId: string, };
