// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Outcome } from "./Outcome";

export type Registration = { action: Action, chord: string, outcome: Outcome, };
