// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingSet } from "./BindingSet";
import type { Conflict } from "./Conflict";
import type { Registration } from "./Registration";

/**
 * Everything the settings screen needs in one answer.
 *
 * `autostart` is read from the registry rather than from the settings
 * file: a player can remove Azure from Task Manager's Startup tab, and
 * the toggle should agree with the machine rather than with what Azure
 * last wrote.
 */
export type ResidencyView = { bindings: BindingSet, 
/**
 * What Windows allowed, per binding. Empty before the first bind.
 */
registrations: Array<Registration>, 
/**
 * Two of Azure's own actions on one chord. Azure's to fix, unlike a
 * refusal.
 */
conflicts: Array<Conflict>, autostart: boolean, 
/**
 * Whether Azure is already elevated, so the interface does not offer
 * a restart that would change nothing.
 */
elevated: boolean, notices: Array<string>, };
