// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Candidate } from "./Candidate";
import type { SourceReport } from "./SourceReport";

export type ScanReport = { candidates: Array<Candidate>, sources: Array<SourceReport>, };
