// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingSet } from "./BindingSet";

export type Settings = { version: number, bindings: BindingSet, 
/**
 * Off unless asked for. A tool that adds itself to startup without
 * being asked is the kind of thing this one is trying not to be.
 */
autostart: boolean, 
/**
 * Whether the player has been told where the window went. Once ever,
 * not once a session.
 */
toldAboutTray: boolean, };
