// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelReport } from "./ChannelReport";
import type { ColorState } from "./ColorState";
import type { DisplayInfo } from "./DisplayInfo";
import type { Environment } from "./Environment";
import type { LutTarget } from "./LutTarget";

/**
 * Everything the surface needs to draw itself once.
 */
export type Snapshot = { channels: Array<ChannelReport>, displays: Array<DisplayInfo>, environment: Environment, enabled: boolean, state: ColorState, target: LutTarget, 
/**
 * Why a stage is missing, if one is. Straight to the event log.
 */
notices: Array<string>, };
