// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelReport } from "./ChannelReport";
import type { ColorState } from "./ColorState";
import type { DisplayInfo } from "./DisplayInfo";
import type { Environment } from "./Environment";
import type { LutTarget } from "./LutTarget";
import type { MatchKind } from "./MatchKind";
import type { Preset } from "./Preset";

/**
 * Everything the surface needs to draw itself once.
 */
export type Snapshot = { channels: Array<ChannelReport>, displays: Array<DisplayInfo>, environment: Environment, enabled: boolean, presets: Array<Preset>, activeId: string, 
/**
 * How the active preset was reached, when the watcher reached it.
 * `None` means someone clicked it.
 */
matchedBy: MatchKind | null, state: ColorState, target: LutTarget, 
/**
 * Why a stage is missing, or what was recovered at startup. Straight
 * to the event log.
 */
notices: Array<string>, };
