// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Launcher } from "./Launcher";
import type { SourceOutcome } from "./SourceOutcome";

export type SourceReport = { launcher: Launcher, outcome: SourceOutcome, };
