// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened with one launcher.
 *
 * Every source answers. Most players have two or three launchers, and
 * five quiet absences must not read as five failures.
 */
export type SourceOutcome = { "kind": "scanned", found: number, } | { "kind": "notInstalled" } | { "kind": "unreadable", reason: string, };
