// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stage } from "./Stage";

export type StageLanding = { stage: Stage, backend: string, ok: boolean, detail: string | null, };
